name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - run: cd 'Textbook Latex'
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          work_in_root_file_dir: true
          continue_on_error: true
          root_file: 'Digital Design Textbook.tex'
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: |
            Digital Design Textbook.pdf
