name: Build LaTeX document

on: [push]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Git repository
      uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}
    - name: Compile LaTeX document
      uses: xu-cheng/latex-action@v3
      with:
        work_in_root_file_dir: true
        continue_on_error: true
        root_file: |
          Textbook-Latex/Digital-Design-Textbook.tex
          Laboratory-Latex/Digital-Design-Labs.tex
    - name: Move Files
      run: mv Textbook-Latex/Digital-Design-Textbook.pdf "Digital Design Textbook.pdf" && mv Laboratory-Latex/Digital-Design-Labs.pdf "Digital Design Labs.pdf"
    - name: Setup Git Config
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
    - name: Commit
      run: |
        git add "Digital Design Textbook.pdf" "Digital Design Labs.pdf"
        git commit -m "Update pdfs"
        git push origin main
