name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - run: cd 'Textbook Latex'
      # - run: cp Digital\ Design\ Textbook.tex
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          continue_on_error: true
          root_file: Digital-Design-Textbook.tex
      - uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: Digital-Design-Textbook.tex
